"""Type stubs for the reclink._core Rust extension module."""

from collections.abc import Sequence

import numpy as np
from numpy.typing import NDArray

# String metrics

def levenshtein(a: str, b: str) -> int: ...
def levenshtein_similarity(a: str, b: str) -> float: ...
def damerau_levenshtein(a: str, b: str) -> int: ...
def damerau_levenshtein_similarity(a: str, b: str) -> float: ...
def hamming(a: str, b: str) -> int: ...
def hamming_similarity(a: str, b: str) -> float: ...
def jaro(a: str, b: str) -> float: ...
def jaro_winkler(a: str, b: str, prefix_weight: float = 0.1) -> float: ...
def cosine(a: str, b: str, n: int = 2) -> float: ...
def jaccard(a: str, b: str) -> float: ...
def sorensen_dice(a: str, b: str) -> float: ...
def weighted_levenshtein(
    a: str,
    b: str,
    insert_cost: float = 1.0,
    delete_cost: float = 1.0,
    substitute_cost: float = 1.0,
    transpose_cost: float = 1.0,
) -> float: ...
def weighted_levenshtein_similarity(
    a: str,
    b: str,
    insert_cost: float = 1.0,
    delete_cost: float = 1.0,
    substitute_cost: float = 1.0,
    transpose_cost: float = 1.0,
) -> float: ...
def token_sort_ratio(a: str, b: str) -> float: ...
def token_set_ratio(a: str, b: str) -> float: ...
def partial_ratio(a: str, b: str) -> float: ...
def lcs_length(a: str, b: str) -> int: ...
def lcs_similarity(a: str, b: str) -> float: ...
def longest_common_substring_length(a: str, b: str) -> int: ...
def longest_common_substring_similarity(a: str, b: str) -> float: ...
def ngram_similarity(a: str, b: str, n: int = 2) -> float: ...
def smith_waterman(
    a: str,
    b: str,
    match_score: float = 2.0,
    mismatch_penalty: float = -1.0,
    gap_penalty: float = -1.0,
) -> float: ...
def smith_waterman_similarity(a: str, b: str) -> float: ...
def phonetic_hybrid(
    a: str,
    b: str,
    phonetic: str = "soundex",
    metric: str = "jaro_winkler",
    phonetic_weight: float = 0.3,
) -> float: ...
def levenshtein_threshold(a: str, b: str, max_distance: int) -> int | None: ...
def damerau_levenshtein_threshold(a: str, b: str, max_distance: int) -> int | None: ...
def match_best(
    query: str,
    candidates: list[str],
    scorer: str = "jaro_winkler",
    threshold: float | None = None,
    workers: int | None = None,
) -> tuple[str, float, int] | None: ...
def match_batch(
    query: str,
    candidates: list[str],
    scorer: str = "jaro_winkler",
    threshold: float | None = None,
    limit: int | None = None,
    workers: int | None = None,
) -> list[tuple[str, float, int]]: ...
def cdist(
    a: Sequence[str],
    b: Sequence[str],
    scorer: str = "jaro_winkler",
    workers: int | None = None,
) -> NDArray[np.float64]: ...

# Phonetic

def soundex(s: str) -> str: ...
def metaphone(s: str) -> str: ...
def double_metaphone(s: str) -> tuple[str, str]: ...
def nysiis(s: str) -> str: ...
def caverphone(s: str) -> str: ...
def cologne_phonetic(s: str) -> str: ...

# Preprocessing

def fold_case(s: str) -> str: ...
def normalize_whitespace(s: str) -> str: ...
def strip_punctuation(s: str) -> str: ...
def standardize_name(s: str) -> str: ...
def remove_stop_words(s: str) -> str: ...
def expand_abbreviations(s: str) -> str: ...
def strip_diacritics(s: str) -> str: ...
def regex_replace(s: str, pattern: str, replacement: str) -> str: ...

# Domain preprocessors

def clean_name(s: str) -> str: ...
def clean_address(s: str) -> str: ...
def clean_company(s: str) -> str: ...
def normalize_email(s: str) -> str: ...
def normalize_url(s: str) -> str: ...
def synonym_expand(s: str, table: dict[str, str]) -> str: ...

# Tokenization & Unicode normalization

def ngram_tokenize(s: str, n: int = 2) -> list[str]: ...
def whitespace_tokenize(s: str) -> list[str]: ...
def normalize_unicode(s: str, form: str = "nfkc") -> str: ...

# Batch preprocessing

def preprocess_batch(strings: list[str], operations: list[str]) -> list[str]: ...
def ngram_tokenize_batch(strings: list[str], n: int = 2) -> list[list[str]]: ...
def whitespace_tokenize_batch(strings: list[str]) -> list[list[str]]: ...
def explain(a: str, b: str, algorithms: list[str] | None = None) -> dict[str, float]: ...

# BK-Tree

class PyBkTree:
    @staticmethod
    def build(strings: list[str], metric: str) -> PyBkTree: ...
    def find_within(self, query: str, max_distance: int) -> list[tuple[str, int, int]]: ...
    def find_nearest(self, query: str, k: int) -> list[tuple[str, int, int]]: ...
    def __len__(self) -> int: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> PyBkTree: ...

# VP-Tree

class PyVpTree:
    @staticmethod
    def build(strings: list[str], metric: str) -> PyVpTree: ...
    def find_within(self, query: str, max_distance: float) -> list[tuple[str, int, float]]: ...
    def find_nearest(self, query: str, k: int) -> list[tuple[str, int, float]]: ...
    def __len__(self) -> int: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> PyVpTree: ...

# N-gram Index

class PyNgramIndex:
    @staticmethod
    def build(strings: list[str], n: int) -> PyNgramIndex: ...
    def search(self, query: str, threshold: int) -> list[tuple[str, int, int]]: ...
    def search_top_k(self, query: str, k: int) -> list[tuple[str, int, int]]: ...
    def __len__(self) -> int: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> PyNgramIndex: ...

# CompositeScorer

class PyCompositeScorer:
    def __init__(self, components: list[tuple[str, float]]) -> None: ...
    @staticmethod
    def preset(name: str) -> PyCompositeScorer: ...
    def similarity(self, a: str, b: str) -> float: ...
    def match_best(
        self,
        query: str,
        candidates: list[str],
        threshold: float | None = None,
    ) -> tuple[str, float, int] | None: ...
    def match_batch(
        self,
        query: str,
        candidates: list[str],
        threshold: float | None = None,
        limit: int | None = None,
    ) -> list[tuple[str, float, int]]: ...

# StreamingMatcher

class PyStreamingMatcher:
    def __init__(
        self,
        query: str,
        scorer: str = "jaro_winkler",
        threshold: float | None = None,
    ) -> None: ...
    def score(self, candidate: str) -> float | None: ...
    def score_chunk(self, candidates: list[str]) -> list[tuple[int, float]]: ...

# TF-IDF

class PyTfIdfMatcher:
    @staticmethod
    def fit(corpus: list[str]) -> PyTfIdfMatcher: ...
    def similarity(self, a: str, b: str) -> float: ...
    def match_batch(
        self,
        query: str,
        candidates: list[str],
        threshold: float | None = None,
    ) -> list[tuple[str, float, int]]: ...
    def __len__(self) -> int: ...

# EM estimation

class PyEmResult:
    m_probs: list[float]
    u_probs: list[float]
    p_match: float
    iterations: int
    converged: bool

def estimate_fellegi_sunter_params(
    vectors: list[list[float]],
    max_iterations: int = 100,
    convergence_threshold: float = 1e-6,
    initial_p_match: float = 0.1,
) -> PyEmResult: ...

# Pipeline

class PyRecord:
    def __init__(self, id: str) -> None: ...
    def set_field(self, name: str, value: str) -> None: ...
    def get_field(self, name: str) -> str | None: ...

class PyMatchResult:
    left_id: str
    right_id: str
    score: float
    scores: list[float]

class PyPipeline:
    def __init__(self) -> None: ...
    def preprocess_lowercase(self, fields: list[str]) -> None: ...
    def preprocess(self, field: str, operations: list[str]) -> None: ...
    def block_exact(self, field: str) -> None: ...
    def block_phonetic(self, field: str, algorithm: str = "soundex") -> None: ...
    def block_sorted_neighborhood(self, field: str, window: int = 3) -> None: ...
    def block_qgram(self, field: str, q: int = 3, threshold: int = 1) -> None: ...
    def block_numeric(self, field: str, bucket_size: float = 5.0) -> None: ...
    def block_date(self, field: str, resolution: str = "year") -> None: ...
    def compare_string(self, field: str, metric: str = "jaro_winkler") -> None: ...
    def compare_exact(self, field: str) -> None: ...
    def compare_numeric(self, field: str, max_diff: float = 10.0) -> None: ...
    def compare_date(self, field: str) -> None: ...
    def compare_phonetic(self, field: str, algorithm: str = "soundex") -> None: ...
    def classify_threshold(self, threshold: float) -> None: ...
    def classify_weighted(self, weights: list[float], threshold: float) -> None: ...
    def classify_fellegi_sunter(
        self,
        m_probs: list[float],
        u_probs: list[float],
        upper: float,
        lower: float,
    ) -> None: ...
    def classify_fellegi_sunter_auto(
        self,
        max_iterations: int = 100,
        convergence_threshold: float = 1e-6,
        initial_p_match: float = 0.1,
    ) -> None: ...
    def cluster_connected_components(self) -> None: ...
    def cluster_hierarchical(self, linkage: str = "single", threshold: float = 0.5) -> None: ...
    def block_lsh(self, field: str, num_hashes: int = 100, num_bands: int = 20) -> None: ...
    def block_canopy(
        self,
        field: str,
        t_tight: float = 0.9,
        t_loose: float = 0.5,
        metric: str = "jaro_winkler",
    ) -> None: ...
    def dedup(self, records: list[PyRecord]) -> list[PyMatchResult]: ...
    def dedup_cluster(self, records: list[PyRecord]) -> list[list[str]]: ...
    def link(
        self,
        left: list[PyRecord],
        right: list[PyRecord],
    ) -> list[PyMatchResult]: ...
