"""Type stubs for the reclink._core Rust extension module."""

from collections.abc import Sequence

import numpy as np
from numpy.typing import NDArray

# String metrics

def levenshtein(a: str, b: str) -> int: ...
def levenshtein_similarity(a: str, b: str) -> float: ...
def damerau_levenshtein(a: str, b: str) -> int: ...
def damerau_levenshtein_similarity(a: str, b: str) -> float: ...
def hamming(a: str, b: str) -> int: ...
def hamming_similarity(a: str, b: str) -> float: ...
def jaro(a: str, b: str) -> float: ...
def jaro_winkler(a: str, b: str, prefix_weight: float = 0.1) -> float: ...
def cosine(a: str, b: str, n: int = 2) -> float: ...
def jaccard(a: str, b: str) -> float: ...
def sorensen_dice(a: str, b: str) -> float: ...
def cdist(
    a: Sequence[str],
    b: Sequence[str],
    scorer: str = "jaro_winkler",
    workers: int | None = None,
) -> NDArray[np.float64]: ...

# Phonetic

def soundex(s: str) -> str: ...
def metaphone(s: str) -> str: ...
def double_metaphone(s: str) -> tuple[str, str]: ...
def nysiis(s: str) -> str: ...

# Preprocessing

def fold_case(s: str) -> str: ...
def normalize_whitespace(s: str) -> str: ...
def strip_punctuation(s: str) -> str: ...
def standardize_name(s: str) -> str: ...

# Tokenization & Unicode normalization

def ngram_tokenize(s: str, n: int = 2) -> list[str]: ...
def whitespace_tokenize(s: str) -> list[str]: ...
def normalize_unicode(s: str, form: str = "nfkc") -> str: ...

# Batch preprocessing

def preprocess_batch(strings: list[str], operations: list[str]) -> list[str]: ...
def ngram_tokenize_batch(strings: list[str], n: int = 2) -> list[list[str]]: ...
def whitespace_tokenize_batch(strings: list[str]) -> list[list[str]]: ...

# EM estimation

class PyEmResult:
    m_probs: list[float]
    u_probs: list[float]
    p_match: float
    iterations: int
    converged: bool

def estimate_fellegi_sunter_params(
    vectors: list[list[float]],
    max_iterations: int = 100,
    convergence_threshold: float = 1e-6,
    initial_p_match: float = 0.1,
) -> PyEmResult: ...

# Pipeline

class PyRecord:
    def __init__(self, id: str) -> None: ...
    def set_field(self, name: str, value: str) -> None: ...
    def get_field(self, name: str) -> str | None: ...

class PyMatchResult:
    left_id: str
    right_id: str
    score: float
    scores: list[float]

class PyPipeline:
    def __init__(self) -> None: ...
    def preprocess_lowercase(self, fields: list[str]) -> None: ...
    def preprocess(self, field: str, operations: list[str]) -> None: ...
    def block_exact(self, field: str) -> None: ...
    def block_phonetic(self, field: str, algorithm: str = "soundex") -> None: ...
    def block_sorted_neighborhood(self, field: str, window: int = 3) -> None: ...
    def block_qgram(self, field: str, q: int = 3, threshold: int = 1) -> None: ...
    def block_numeric(self, field: str, bucket_size: float = 5.0) -> None: ...
    def block_date(self, field: str, resolution: str = "year") -> None: ...
    def compare_string(self, field: str, metric: str = "jaro_winkler") -> None: ...
    def compare_exact(self, field: str) -> None: ...
    def compare_numeric(self, field: str, max_diff: float = 10.0) -> None: ...
    def compare_date(self, field: str) -> None: ...
    def compare_phonetic(self, field: str, algorithm: str = "soundex") -> None: ...
    def classify_threshold(self, threshold: float) -> None: ...
    def classify_weighted(self, weights: list[float], threshold: float) -> None: ...
    def classify_fellegi_sunter(
        self,
        m_probs: list[float],
        u_probs: list[float],
        upper: float,
        lower: float,
    ) -> None: ...
    def classify_fellegi_sunter_auto(
        self,
        max_iterations: int = 100,
        convergence_threshold: float = 1e-6,
        initial_p_match: float = 0.1,
    ) -> None: ...
    def cluster_connected_components(self) -> None: ...
    def cluster_hierarchical(self, linkage: str = "single", threshold: float = 0.5) -> None: ...
    def block_lsh(self, field: str, num_hashes: int = 100, num_bands: int = 20) -> None: ...
    def block_canopy(
        self,
        field: str,
        t_tight: float = 0.9,
        t_loose: float = 0.5,
        metric: str = "jaro_winkler",
    ) -> None: ...
    def dedup(self, records: list[PyRecord]) -> list[PyMatchResult]: ...
    def dedup_cluster(self, records: list[PyRecord]) -> list[list[str]]: ...
    def link(
        self,
        left: list[PyRecord],
        right: list[PyRecord],
    ) -> list[PyMatchResult]: ...
